Repository apache/skywalking-banyandb-java-client, pull requests merged in 2022-11, with the labels that each got.

#23 Generate dependencies license
  .github/workflows/ci.yaml
  .licenserc.yaml
  dist-material/LICENSE
  dist-material/LICENSE.tpl
  dist-material/NOTICE
  dist-material/licenses/license-com.google.android-annotations.txt
  dist-material/licenses/license-com.google.protobuf-protobuf-java-util.txt
  dist-material/licenses/license-com.google.protobuf-protobuf-java.txt
  dist-material/licenses/license-com.google.re2j-re2j.txt
  dist-material/licenses/license-org.checkerframework-checker-compat-qual.txt
  dist-material/licenses/license-org.checkerframework-checker-qual.txt
  dist-material/licenses/license-org.codehaus.mojo-animal-sniffer-annotations.txt
Labels: documentation

#24 Release BanyanDB Java Client v0.2.0, and begin next release.
  pom.xml
Labels: documentation

#25 Fix wrong offset if tag is null
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureWrite.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/StreamWrite.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamWriteTest.java
Labels: bug

#26 Support timestamp lazy initialization for StreamWrite.
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractWrite.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/StreamWrite.java
Labels: enhancement
