Repository apache/skywalking-banyandb-java-client, pull requests merged in 2022-05, with the labels that each got.

#12 Fix wrong index rule binding for Measure
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractQuery.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClient.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/DataPoint.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureQuery.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureWrite.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/PairQueryCondition.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/RowEntity.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/StreamQuery.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/TagAndValue.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/Value.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/Measure.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/TagFamilySpec.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientMeasureQueryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientMeasureWriteTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamQueryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamWriteTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/ITBanyanDBMeasureQueryTests.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/ITBanyanDBStreamQueryTests.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/MeasureMetadataRegistryTest.java
Labels: bug

#14 Abandon shaded netty lib
  pom.xml
  src/main/java/org/apache/skywalking/banyandb/v1/client/grpc/channel/DefaultChannelFactory.java
Labels: enhancement

#16 Bump up server version for IT
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientTestCI.java
Labels: test

#17 Fix year in NOTICE file
  NOTICE
Labels: documentation
