Repository apache/skywalking-banyandb-java-client, pull requests merged in 2022-10, with the labels that each got.

#19 Remove powermock and update mockito
  .github/workflows/ci.yaml
  pom.xml
  src/test/java/org/apache/skywalking/banyandb/v1/client/AbstractBanyanDBClientTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientMeasureQueryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamQueryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamWriteTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/grpc/ExceptionTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/grpc/channel/ChannelManagerTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/IndexRuleBindingMetadataRegistryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/IndexRuleMetadataRegistryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/MeasureMetadataRegistryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/PropertyStoreTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/StreamMetadataRegistryTest.java
Labels: bug, enhancement

#18 Bump up proto files
  CHANGES.md
  README.md
  pom.xml
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractBulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractCriteria.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractQuery.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/And.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClient.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureBulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureQuery.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/Or.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/PairQueryCondition.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/StreamBulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/StreamQuery.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/grpc/GRPCStreamServiceStatus.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/grpc/MetadataClient.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/Group.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/GroupMetadataRegistry.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/IndexRule.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/IndexRuleBindingMetadataRegistry.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/IndexRuleMetadataRegistry.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/IntervalRule.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/MeasureMetadataRegistry.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/PropertyStore.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/ResourceExist.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/StreamMetadataRegistry.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/TagFamilySpec.java
  src/main/proto/banyandb/v1/banyandb-common.proto
  src/main/proto/banyandb/v1/banyandb-database.proto
  src/main/proto/banyandb/v1/banyandb-measure.proto
  src/main/proto/banyandb/v1/banyandb-model.proto
  src/main/proto/banyandb/v1/banyandb-property.proto
  src/main/proto/banyandb/v1/banyandb-stream.proto
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientMeasureQueryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamQueryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientTestCI.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/ITBanyanDBMeasureQueryTests.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/ITBanyanDBPropertyTests.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/ITBanyanDBStreamQueryTests.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/IndexRuleMetadataRegistryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/metadata/PropertyStoreTest.java
Labels: enhancement

#20 Update banyandb-common.proto
  src/main/proto/banyandb/v1/banyandb-common.proto
Labels: bug

#21 Expose eq for IDQuery and existence check methods
  src/main/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClient.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/PairQueryCondition.java
Labels: enhancement

#22 Improve single condition criteria
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractQuery.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientMeasureQueryTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamQueryTest.java
Labels: enhancement
