Repository apache/skywalking-banyandb-java-client, pull requests merged in 2024-07, with the labels that each got.

#62 Add ToString annotation to Tag
  src/main/java/org/apache/skywalking/banyandb/v1/client/Tag.java
Labels: enhancement

#63 Enhance the BulkWriteProcessor
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/DataCarrier.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/EnvUtil.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/buffer/ArrayBlockingQueueBuffer.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/buffer/Buffer.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/buffer/BufferStrategy.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/buffer/Channels.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/buffer/QueueBuffer.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/common/AtomicRangeInteger.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/BulkConsumePool.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/ConsumeDriver.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/ConsumerCannotBeCreatedException.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/ConsumerPool.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/ConsumerPoolFactory.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/ConsumerThread.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/IConsumer.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/IDriver.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/consumer/MultipleChannelsConsumer.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/partition/IDataPartitioner.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/partition/ProducerThreadPartitioner.java
  src/main/java/org/apache/skywalking/banyandb/commons/datacarrier/partition/SimpleRollingPartitioner.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractBulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClient.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/BulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureBulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/StreamBulkWriteProcessor.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientMeasureWriteTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClientStreamWriteTest.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/ITBanyanDBMeasureQueryTests.java
  src/test/java/org/apache/skywalking/banyandb/v1/client/ITBanyanDBStreamQueryTests.java
Labels: enhancement

#64 Add timeout in the doc
  README.md
Labels: documentation

#65 Document how to use query tracing
  README.md
Labels: documentation

#66 Provide a new method to order data by timestamp
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractQuery.java
Labels: enhancement

#67 Remove duplicate orderBy method in measure query.
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureQuery.java
Labels: duplicate
