Repository apache/skywalking-banyandb-java-client, pull requests merged in 2025-08, with the labels that each got.

#90 Bump up proto for replicas config and TLS option simplification
  CHANGES.md
  src/main/java/org/apache/skywalking/banyandb/v1/client/Options.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/grpc/channel/DefaultChannelFactory.java
  src/main/proto/banyandb/v1/banyandb-common.proto
Labels: dependencies

#91 Add write histogram for client.
  CHANGES.md
  pom.xml
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractBulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/BanyanDBClient.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/MeasureBulkWriteProcessor.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/Options.java
  src/main/java/org/apache/skywalking/banyandb/v1/client/StreamBulkWriteProcessor.java
Labels: enhancement

#92 Fix timer doesn't finish
  src/main/java/org/apache/skywalking/banyandb/v1/client/AbstractBulkWriteProcessor.java
Labels: bug

#93 Bump up env and add setup doc for IDEA
  .github/workflows/ci.yaml
  .mvn/wrapper/maven-wrapper.properties
  CHANGES.md
  README.md
  pom.xml
Labels: documentation
